version: '3'
services:
  app:
    container_name: docker-FullStck-mongo
    restart: always
    build: .
    ports:
      - '8080:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'